/**
 * TypeScript adapter for WASM GraphEngine
 * Provides type-safe interface for working with Rust WASM module
 */

import type { Edge, Node } from '@/entities/map'
import { initWasmModule } from './wasm-loader'

// WASM module types (generated by wasm-pack)
interface WasmGraphEngine {
  // Core
  init_renderer(canvas: HTMLCanvasElement): void
  load_graph(jsonData: string): void
  run_layout(options_json: string): string
  render(): void
  resize(width: number, height: number): boolean
  // Viewport
  pan(dx: number, dy: number): void
  zoom_at(screen_x: number, screen_y: number, factor: number): void
  get_zoom(): number
  fit_view(padding: number): void
  // Selection
  set_selected(node_id: string | null): void
  set_focused(node_id: string | null): void
  set_dimmed(node_ids: string): void
  hit_test(screen_x: number, screen_y: number): string | undefined
  // Stats
  node_count(): number
  edge_count(): number
  // Theme & Atlases
  set_theme(json: string): void
  load_font_atlas_data(
    image_data: Uint8Array,
    width: number,
    height: number,
    metrics_json: string
  ): void
  load_icon_atlas_data(
    image_data: Uint8Array,
    width: number,
    height: number,
    icons_json: string
  ): void
}

interface WasmModule {
  default?: () => Promise<unknown>
  init?: () => void
  GraphEngine: new () => WasmGraphEngine
}

export interface GraphData {
  nodes: GraphNode[]
  edges: GraphEdge[]
}

export interface GraphNode {
  id: string
  label: string
  description?: string
  node_type: string
  position: { x: number; y: number }
  size?: { width: number; height: number }
}

export interface GraphEdge {
  id: string
  source: string
  target: string
  relation_type: string
  label?: string
  strength: number
  bidirectional: boolean
}

export interface GraphStats {
  nodes: number
  edges: number
  nodesRendered: number
  edgesRendered: number
}

/**
 * TypeScript wrapper for WASM GraphEngine
 */
export class GraphEngine {
  private wasmEngine: WasmGraphEngine | null = null

  async init(canvas: HTMLCanvasElement): Promise<void> {
    this.canvas = canvas

    try {
      // Dynamic import of WASM module
      const wasm = await import('../wasm/graph_engine')

      // Initialize WASM
      await initWasmModule(wasm as WasmModule)
      this.wasmModule = wasm as WasmModule

      // Create engine instance
      this.wasmEngine = new wasm.GraphEngine()
      this.wasmEngine.init_renderer(canvas)
    } catch (error) {
      throw new Error(`Failed to initialize WASM engine: ${error}`)
    }
  }

  /**
   * Load graph from application data
   */
  loadGraph(nodes: Node[], edges: Edge[]): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    const graphData: GraphData = {
      nodes: nodes.map(node => this.transformNode(node)),
      edges: edges.map(edge => this.transformEdge(edge))
    }

    this.wasmEngine.load_graph(JSON.stringify(graphData))
  }

  /**
   * Run layout algorithm
   */
  runLayout(optionsJson: string): string {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    return this.wasmEngine.run_layout(optionsJson)
  }

  /**
   * Render current frame
   */
  render(): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.render()
  }

  /**
   * Pan viewport
   */
  pan(dx: number, dy: number): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.pan(dx, dy)
  }

  /**
   * Zoom at screen point
   */
  zoomAt(screenX: number, screenY: number, factor: number): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.zoom_at(screenX, screenY, factor)
  }

  /**
   * Get current zoom level
   */
  getZoom(): number {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    return this.wasmEngine.get_zoom()
  }

  /**
   * Fit view to show all nodes
   */
  fitView(padding: number): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.fit_view(padding)
  }

  /**
   * Resize canvas
   */
  resize(width: number, height: number): boolean {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    return this.wasmEngine.resize(width, height)
  }

  /**
   * Select node
   */
  setSelected(nodeId: string | null): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.set_selected(nodeId)
  }

  /**
   * Focus node
   */
  setFocused(nodeId: string | null): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.set_focused(nodeId)
  }

  /**
   * Set dimmed nodes
   */
  setDimmed(nodeIds: string[]): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.set_dimmed(JSON.stringify(nodeIds))
  }

  /**
   * Hit test at screen coordinates
   */
  hitTest(screenX: number, screenY: number): string | undefined {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    return this.wasmEngine.hit_test(screenX, screenY)
  }

  /**
   * Get node count
   */
  nodeCount(): number {
    if (!this.wasmEngine) {
      return 0
    }

    return this.wasmEngine.node_count()
  }

  /**
   * Get edge count
   */
  edgeCount(): number {
    if (!this.wasmEngine) {
      return 0
    }

    return this.wasmEngine.edge_count()
  }

  /**
   * Set theme colors
   */
  setTheme(json: string): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.set_theme(json)
  }

  /**
   * Load font atlas
   */
  loadFontAtlasData(
    imageData: Uint8Array,
    width: number,
    height: number,
    metricsJson: string
  ): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.load_font_atlas_data(imageData, width, height, metricsJson)
  }

  /**
   * Load icon atlas
   */
  loadIconAtlasData(imageData: Uint8Array, width: number, height: number, iconsJson: string): void {
    if (!this.wasmEngine) {
      throw new Error('Engine not initialized')
    }

    this.wasmEngine.load_icon_atlas_data(imageData, width, height, iconsJson)
  }

  /**
   * Cleanup resources
   */
  dispose(): void {
    this.wasmEngine = null
    this.wasmModule = null
    this.canvas = null
  }

  // === Private helpers ===

  private transformNode(node: Node): GraphNode {
    return {
      id: node.id,
      label: node.label,
      description: node.description,
      node_type: node.type,
      position: node.position,
      size: { width: 180, height: 100 }
    }
  }

  private transformEdge(edge: Edge): GraphEdge {
    return {
      id: edge.id,
      source: edge.sourceNodeId,
      target: edge.targetNodeId,
      relation_type: edge.relationType,
      label: edge.label,
      strength: edge.strength || 0.5,
      bidirectional: edge.bidirectional || false
    }
  }
}
