/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init: () => void;
export const __wbg_graphengine_free: (a: number, b: number) => void;
export const graphengine_edge_count: (a: number) => number;
export const graphengine_fit_view: (a: number, b: number) => void;
export const graphengine_get_all_positions: (a: number) => [number, number];
export const graphengine_get_viewport: (a: number) => [number, number];
export const graphengine_get_visible_nodes: (a: number) => [number, number];
export const graphengine_get_zoom: (a: number) => number;
export const graphengine_hit_test: (a: number, b: number, c: number) => [number, number];
export const graphengine_init_layout: (a: number, b: number, c: number) => [number, number];
export const graphengine_init_renderer: (a: number, b: any) => [number, number];
export const graphengine_is_converged: (a: number) => number;
export const graphengine_is_layout_running: (a: number) => number;
export const graphengine_load_font_atlas_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const graphengine_load_graph: (a: number, b: number, c: number) => [number, number];
export const graphengine_load_icon_atlas_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const graphengine_load_sdf_atlas_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const graphengine_new: () => number;
export const graphengine_node_count: (a: number) => number;
export const graphengine_pan: (a: number, b: number, c: number) => void;
export const graphengine_render: (a: number) => void;
export const graphengine_resize: (a: number, b: number, c: number) => number;
export const graphengine_run_layout: (a: number, b: number, c: number) => [number, number, number, number];
export const graphengine_set_dimmed: (a: number, b: number, c: number) => void;
export const graphengine_set_focused: (a: number, b: number, c: number) => void;
export const graphengine_set_selected: (a: number, b: number, c: number) => void;
export const graphengine_set_theme: (a: number, b: number, c: number) => [number, number];
export const graphengine_set_viewport: (a: number, b: number, c: number) => [number, number];
export const graphengine_step_layout: (a: number, b: number) => [number, number];
export const graphengine_update_node_position: (a: number, b: number, c: number, d: number, e: number) => void;
export const graphengine_zoom_at: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
