/**
 * Hook for managing the WASM graph engine
 */

import { useCallback, useEffect, useRef, useState } from 'react'
import type { GraphEngineState, LayoutOptions, LayoutResult, Node, Edge } from '../lib/types'
import { transformToWasm, layoutOptionsToWasm, applyPositions } from '../lib/transform'

// WASM module type (will be generated by wasm-pack)
interface GraphEngine {
  new(): GraphEngine
  init_renderer(canvas: HTMLCanvasElement): void
  resize(width: number, height: number): void
  load_graph(json: string): void
  run_layout(optionsJson: string): string
  init_layout(optionsJson: string): void
  step_layout(iterations: number): string
  is_layout_running(): boolean
  is_converged(): boolean
  hit_test(screenX: number, screenY: number): string | null
  update_node_position(id: string, x: number, y: number): void
  get_all_positions(): string
  get_visible_nodes(): string
  set_selected(nodeId: string | null): void
  set_focused(nodeId: string | null): void
  set_dimmed(nodeIds: string): void
  pan(dx: number, dy: number): void
  zoom_at(screenX: number, screenY: number, factor: number): void
  get_zoom(): number
  fit_view(padding: number): void
  get_viewport(): string
  set_viewport(json: string): void
  render(): void
  node_count(): number
  edge_count(): number
}

interface WasmModule {
  GraphEngine: new () => GraphEngine
}

// Singleton for WASM module
let wasmModule: WasmModule | null = null
let wasmLoadPromise: Promise<WasmModule> | null = null

async function loadWasm(): Promise<WasmModule> {
  if (wasmModule) return wasmModule

  if (wasmLoadPromise) return wasmLoadPromise

  wasmLoadPromise = (async () => {
    try {
      // Dynamic import of WASM module
      // The path will be resolved by Vite's WASM plugin
      const module = await import('../pkg/graph_engine')
      wasmModule = module as WasmModule
      return wasmModule
    } catch (error) {
      wasmLoadPromise = null
      throw error
    }
  })()

  return wasmLoadPromise
}

interface UseGraphEngineOptions {
  canvas: HTMLCanvasElement | null
  onPositionsUpdate?: (nodes: Node[]) => void
}

export function useGraphEngine({ canvas, onPositionsUpdate }: UseGraphEngineOptions) {
  const engineRef = useRef<GraphEngine | null>(null)
  const animationFrameRef = useRef<number | null>(null)

  const [state, setState] = useState<GraphEngineState>({
    isReady: false,
    isLoading: true,
    error: null,
    nodeCount: 0,
    edgeCount: 0,
  })

  // Store nodes for position updates
  const nodesRef = useRef<Node[]>([])

  // Initialize WASM and engine
  useEffect(() => {
    if (!canvas) return

    let mounted = true

    const init = async () => {
      try {
        const wasm = await loadWasm()
        if (!mounted) return

        const engine = new wasm.GraphEngine()
        engine.init_renderer(canvas)
        engine.resize(canvas.width, canvas.height)

        engineRef.current = engine

        setState({
          isReady: true,
          isLoading: false,
          error: null,
          nodeCount: 0,
          edgeCount: 0,
        })
      } catch (error) {
        if (!mounted) return
        setState(s => ({
          ...s,
          isLoading: false,
          error: error instanceof Error ? error.message : 'Failed to load WASM',
        }))
      }
    }

    init()

    return () => {
      mounted = false
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current)
      }
    }
  }, [canvas])

  // Load graph data
  const loadGraph = useCallback((nodes: Node[], edges: Edge[]) => {
    const engine = engineRef.current
    if (!engine) return

    nodesRef.current = nodes
    const json = transformToWasm(nodes, edges)
    engine.load_graph(json)

    setState(s => ({
      ...s,
      nodeCount: engine.node_count(),
      edgeCount: engine.edge_count(),
    }))
  }, [])

  // Run layout (blocking)
  const runLayout = useCallback((options: LayoutOptions): LayoutResult | null => {
    const engine = engineRef.current
    if (!engine) return null

    const resultJson = engine.run_layout(layoutOptionsToWasm(options))
    const result = JSON.parse(resultJson) as LayoutResult

    // Update positions
    if (onPositionsUpdate) {
      const positionsJson = engine.get_all_positions()
      const updatedNodes = applyPositions(nodesRef.current, positionsJson)
      nodesRef.current = updatedNodes
      onPositionsUpdate(updatedNodes)
    }

    return result
  }, [onPositionsUpdate])

  // Start animated layout
  const startAnimatedLayout = useCallback((options: LayoutOptions) => {
    const engine = engineRef.current
    if (!engine) return

    engine.init_layout(layoutOptionsToWasm(options))

    // Animation loop
    const animate = () => {
      if (!engine.is_layout_running()) {
        animationFrameRef.current = null
        return
      }

      // Run 10 iterations per frame
      engine.step_layout(10)
      engine.render()

      // Update positions callback
      if (onPositionsUpdate) {
        const positionsJson = engine.get_all_positions()
        const updatedNodes = applyPositions(nodesRef.current, positionsJson)
        nodesRef.current = updatedNodes
        onPositionsUpdate(updatedNodes)
      }

      animationFrameRef.current = requestAnimationFrame(animate)
    }

    animationFrameRef.current = requestAnimationFrame(animate)
  }, [onPositionsUpdate])

  // Stop animated layout
  const stopLayout = useCallback(() => {
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current)
      animationFrameRef.current = null
    }
  }, [])

  // Render frame
  const render = useCallback(() => {
    engineRef.current?.render()
  }, [])

  // Resize
  const resize = useCallback((width: number, height: number) => {
    engineRef.current?.resize(width, height)
  }, [])

  // Hit test
  const hitTest = useCallback((screenX: number, screenY: number): string | null => {
    return engineRef.current?.hit_test(screenX, screenY) ?? null
  }, [])

  // Update node position (drag)
  const updateNodePosition = useCallback((id: string, x: number, y: number) => {
    engineRef.current?.update_node_position(id, x, y)
  }, [])

  // Selection
  const setSelected = useCallback((nodeId: string | null) => {
    engineRef.current?.set_selected(nodeId)
  }, [])

  const setFocused = useCallback((nodeId: string | null) => {
    engineRef.current?.set_focused(nodeId)
  }, [])

  const setDimmed = useCallback((nodeIds: string[]) => {
    engineRef.current?.set_dimmed(JSON.stringify(nodeIds))
  }, [])

  // Viewport
  const pan = useCallback((dx: number, dy: number) => {
    engineRef.current?.pan(dx, dy)
  }, [])

  const zoomAt = useCallback((screenX: number, screenY: number, factor: number) => {
    engineRef.current?.zoom_at(screenX, screenY, factor)
  }, [])

  const getZoom = useCallback((): number => {
    return engineRef.current?.get_zoom() ?? 1
  }, [])

  const fitView = useCallback((padding = 0.1) => {
    engineRef.current?.fit_view(padding)
  }, [])

  // Get visible nodes for DOM overlay
  const getVisibleNodes = useCallback((): string[] => {
    const json = engineRef.current?.get_visible_nodes()
    if (!json) return []
    return JSON.parse(json) as string[]
  }, [])

  return {
    state,
    loadGraph,
    runLayout,
    startAnimatedLayout,
    stopLayout,
    render,
    resize,
    hitTest,
    updateNodePosition,
    setSelected,
    setFocused,
    setDimmed,
    pan,
    zoomAt,
    getZoom,
    fitView,
    getVisibleNodes,
  }
}
